#! /bin/sh

if [ ! -e "deploy.json" ]; then
    echo "deploy.json not found." 1>&2
    exit 1
fi

DEPLOY_NAMESPACE=$(cat deploy.json | jq -r ".namespace")
DEPLOY_NAME=$(cat deploy.json | jq -r ".name")

DEPLOY_DOCKER_REGISTRY="registry.comame.dev"

DATE=$(date +%Y%m%d-%H%M%S)

eval "docker build -t $DEPLOY_DOCKER_REGISTRY/$DEPLOY_NAME:$DATE ."
eval "docker tag $DEPLOY_DOCKER_REGISTRY/$DEPLOY_NAME:$DATE $DEPLOY_DOCKER_REGISTRY/$DEPLOY_NAME:latest"
eval "docker push $DEPLOY_DOCKER_REGISTRY/$DEPLOY_NAME:$DATE"
eval "docker push $DEPLOY_DOCKER_REGISTRY/$DEPLOY_NAME:latest"

eval "kubectl rollout restart deploy/$DEPLOY_NAME -n $DEPLOY_NAMESPACE"
